testing: False

sweep_counts: 12
early_stopping_patience: 20

# task: birads
# task: mass_shape
task: pathology
model: resnet50

gpu_devices: "0, 1, 2, 3"
gpu_device_count: 4
workers: False
num_workers: 4



folders:
  data: ./data/dataset
  outputs: ./outputs
  assessment: ${folders.data}/assessment
  mass_shape: ${folders.data}/mass_shape
  pathology: ${folders.data}/pathology
  plots_dir: ${folders.outputs}/graphs
  cur_plot: ${folders.plots_dir}
  loss: ${folders.cur_plot}/loss_function.png
  accuracy: ${folders.cur_plot}/accuracy.png
  f1: ${folders.cur_plot}/f1.png
  report: ${folders.cur_plot}/classification_report.png

preprocessing:
  # image_size: [224, 224]
  image_size: [256, 256]
  norm:
      mean: [0.485, 0.456, 0.406] 
      std: [0.229, 0.224, 0.225]

hp:
  batch_size: 32
  lr: 0.01
  weight_decay: 0.01
  epochs: 2
  label_smoothing: 0.25
  lr_patience: 4
  fc_layer: 512


classes_per_task:
  pathology: 2
  mass_shape: 4
  birads: 5
  breast_density: 4

class_names:
  assessment: ["0", "3", "4", "5"]
  pathology: ["MALIGNANT", "BENIGN"]
  mass_shape: ["OVAL", "LOBULATED", "IRREGULAR", "ROUND"]
  breast_density: ["1", "2", "3", "4"]

seed: 42

# DDP settings

backend: nccl # nccl, gloo, etc.