method: grid
metric: 
  goal: maximize
  name: val/accuracy
  target: 93
parameters: 
  epochs:
    values: [20]
  lr: 
    values: [5.5e-3]
  weight_decay: 
    values: [1e-3]
  batch_size: 
    values: [32]
  label_smoothing:
    values:  [0]
  fc_layer: 
    values: [1024]
